name: Full theme release automation
on:
  push:
    branches:
      - main
jobs:
  automate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10.5'
    - name: Install Python dependencies
      uses: py-actions/py-dependency-install@v4
      with:
        path: ".github/requirements.txt"
    - name: Extract any new zip files
      run: python3 .github/extract.py
    - name: Release any new themes
      run: python3 .github/release.py -n
    - name: Update README
      run: python3 .github/generate.py
    - name: Commit and push changes
      uses: actions-js/push@v1.3
      with:
        author_name: 'OnionBot'
        message: 'Theme release automation'
        github_token: ${{ secrets.GITHUB_TOKEN }}
