name: Validate themes
on:
  push:
    branches-ignore:
      - main
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        sparse-checkout: |
          .github
          themes
    - uses: actions/setup-python@v4
      with:
        python-version: '3.12.3'
    - name: Install Python dependencies
      uses: py-actions/py-dependency-install@v4
      with:
        path: ".github/requirements.txt"
    - name: Validating themes
      run: |
        echo using $(python3 --version)
        python3 .github/validation.py
